---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install update (CentOS)
    tags: always
    yum:
      name: '*'
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:

    - name: install Elastik Stack (Ubuntu)
      apt:
        name:
          - elasticsearch
          - kibana
          - logstash
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: install Elastik Stack (CentOS)
      yum:
        name:
          - elasticsearch
          - kibana
          - logstash
        state: latest
      when: ansible_distribution == "CentOS"


- hosts: file_servers
  become: true
  tasks:

    - name: install Elastik Stack (Ubuntu)
      apt:
        name:
          - elasticsearch
          - kibana
          - logstash
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: install Elastik Stack (CentOS)
      yum:
        name:
          - elasticsearch
          - kibana
          - logstash
        state: latest
      when: ansible_distribution == "CentOS"


- hosts: workstations
  become: true
  tasks:

    - name: install Elastik Stack (Ubuntu)
      apt:
        name:
          - elasticsearch
          - kibana
          - logstash
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: install Elastik Stack (CentOS)
      yum:
        name:
          - elasticsearch
          - kibana
          - logstash
        state: latest
      when: ansible_distribution == "CentOS"
